[global.config]
as = 65000
router-id = "192.168.255.1"

[[neighbors]]
[neighbors.config]
neighbor-address = "fd77:bb::2"
peer-as = 65001

[[neighbors.afi-safis]]
[neighbors.afi-safis.config]
afi-safi-name = "ls"
